# Generated by Django 3.2.3 on 2021-05-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('narrator', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Audiobook',
                'verbose_name_plural': 'Audiobooks',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='PodcastParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(blank=True, max_length=100, null=True)),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.podcast')),
            ],
            options={
                'verbose_name': 'Podcast Participant',
                'verbose_name_plural': 'Podcast Participants',
            },
        ),
    ]
